### ISSUE TITLE
No carousel images on 8.0.5

### ISSUE THREAD

**Issue by clemens-tolboom** [onatalushko/jcaurucel#11]
I have error in Firefox 

> ReferenceError: event is not defined
> Drupal.jcarousel.attachEvents()
>  jcarousel.js:87
> Drupal.behaviors.jcarousel.attach/<()
>  jcarousel.js:28
> .each()
>  jquery.min.js:2
> n.prototype.each()
>  jquery.min.js:2
> Drupal.behaviors.jcarousel.attach()
>  jcarousel.js:11
> Drupal.attachBehaviors()
>  drupal.js:168
> <anonymous>
>  drupal.js:178
> t()
>  ready.min.js:4
>  jcarousel.js:87:9

Chrome reports way more errors

> Notice: Undefined index: ajax in _jcarousel_generate_attributes() (line 639 of sites/example.d8/modules/contrib/jcaroucel/jcarousel.module).
> _jcarousel_generate_attributes(Array, Array) (Line: 556)
> template_preprocess_jcarousel(Array, 'jcarousel', Array) (Line: 294)
> Drupal\Core\Theme\ThemeManager->render('jcarousel', Array) (Line: 438)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array) (Line: 933)
> render(Array) (Line: 906)
> Drupal\views\Plugin\views\field\Field->render_item(0, Array) (Line: 1153)
> Drupal\views\Plugin\views\field\FieldPluginBase->advancedRender(Object) (Line: 224)
> template_preprocess_views_view_field(Array, 'views_view_field', Array) (Line: 294)
> Drupal\Core\Theme\ThemeManager->render(Array, Array) (Line: 438)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array) (Line: 1710)
> Drupal\views\Plugin\views\field\FieldPluginBase->theme(Object) (Line: 769)
> Drupal\views\Plugin\views\style\StylePluginBase->elementPreRenderRow(Array)
> call_user_func(Array, Array) (Line: 384)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array) (Line: 717)
> Drupal\views\Plugin\views\style\StylePluginBase->renderFields(Array) (Line: 586)
> Drupal\views\Plugin\views\style\StylePluginBase->renderGrouping(Array, Array, 1) (Line: 473)
> Drupal\views\Plugin\views\style\StylePluginBase->render(Array) (Line: 2121)
> Drupal\views\Plugin\views\display\DisplayPluginBase->render() (Line: 129)
> Drupal\webprofiler\Views\TraceableViewExecutable->render() (Line: 175)
> Drupal\views\Plugin\views\display\Page->execute() (Line: 1592)
> Drupal\views\ViewExecutable->executeDisplay('page_1', Array) (Line: 83)
> Drupal\views\Element\View::preRenderViewElement(Array)
> call_user_func(Array, Array) (Line: 384)
> Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
> Drupal\Core\Render\Renderer->render(Array, ) (Line: 231)
> Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent{closure}() (Line: 577)
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 232)
> Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 122)
> Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 95)
> Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
> call_user_func(Array, Object, 'kernel.view', Object) (Line: 61)
> Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object, 'kernel.view', Object) (Line: 116)
> Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 124)
> Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 144)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 62)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 53)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 211)
> Drupal\page_cache\StackMiddleware\PageCache->fetch(Object, 1, 1) (Line: 125)
> Drupal\page_cache\StackMiddleware\PageCache->lookup(Object, 1, 1) (Line: 79)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 51)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 42)
> Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 55)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
> Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 637)
> Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

![jcarousel___cygnis_dev_voorbeeld-site_nl](https://cloud.githubusercontent.com/assets/371014/13952440/a53b3874-f036-11e5-9e93-2f316f6b09c8.png)

**Comment by onatalushko** [comment]
Hi

Thank you for testing this project.
Fix commited.
Please check if issue still present in updated version.

Thanks
