### ISSUE TITLE
Drupal 8 - jCarousel won't work (no controls, div doesn't behave as it should)

### ISSUE THREAD

**Issue by Bendzs** [onatalushko/jcaurucel#12]
Good day!

I love the simplicity of this carousel menu, so I've tried to add it to my Drupal 8 site, without luck. After following the instructions carefully and setting up the view and block, I've tried adding a few nodes to check if it works, but for somewhat reason the carousel doesn't behave as it should, at all. Neither there are any controls shown, the elements (title and image field of certain content type) simply appear in a grid layout after each other, running out of the container's limits (no carousel "breakpoint"). There are no JS errors during page load. Am I missing something?

Attached two screenshots, the first one shows how the supposed jCarousel div appears on my site, the second one is the HTML code of the jCarousel div in question:

![carousel1](https://cloud.githubusercontent.com/assets/23459663/20276471/a98c4b22-aa9c-11e6-8f36-99875ff1321d.png)

![carousel2](https://cloud.githubusercontent.com/assets/23459663/20276470/a9870fa4-aa9c-11e6-86fb-63be9a670dcd.png)

Thanks in advance!
Bendzs

**Comment by onatalushko** [comment]
Could you tell me your browser version and drupal version ?

**Comment by Bendzs** [comment]
Drupal: 8.2.0 (October release)
Browser(s): Firefox 49.0.2 (up-to-date), Chrome 54.0.2840.99 (up-to-date), Opera 29.0.1795.60 (older version)

Drupal's cache is cleared, so that shouldn't cause the problem.

The autoscroll option seems to work in Opera and Chrome (no controls though), could that setting be the reason for having no control buttons?

Either way, I assume the module should be working in any browser.

**Comment by prshntdrupal** [comment]
@Bendzs how did you made it work.

**Comment by Bendzs** [comment]
@prshntdrupal Couldn't find the actual cause of the problem (I'm not that experienced in jQuery), so I've solved it by directly modifying the jcarousel CSS to customize spacing and transitions to fit to my "Carousel Content Preview" View type.

I only needed an "ad slideshow-ish" auto-scrolling block anyway, and it perfectly fulfills that role (big thanks to the author for the module and easy setup).

On another note: Firefox doesn't even load the carousel's CSS properly, and - based on my lately experiences with the browser (whole Flash based sites not working properly, problems like comboboxes without values on PHP based forms while other browsers have no such problems, and the whacky jQuery script handling that possibly causes the problems with this module too - I am sure that the module has not much to do with the problems mentioned above, rather the Mozilla team should be doing actual bugfixes in such site-breaking bugs.

Also, another pseudo-permanent solution I've used to work around browser problems: "Our site uses the most up-to-date versions of HTML5, CSS and JavaScript, if you're experiencing problems viewing this site, please have a look in another browser, it might be a slight compatibility problem." :)

**Comment by onatalushko** [comment]
Hi all
Sorry for delay with resolving this issue, I'll revalidate it in a week

**Comment by prshntdrupal** [comment]
@onatalushko no worries and thanks for this great module.

For easy replication, this issue is only when auto carousel is used.

**Comment by onatalushko** [comment]
Hi all 
Thanks to @mh35 issue is fixed. Please check
